
import {L} from '../language';
import {BookOpen,ArrowUpRight,FileText} from 'lucide-react';
import {LabHeader} from '../simulator-nav';
import sourceChapters from './content.json';
import {getServerLanguage} from '../../lib/i18n/server';
import type {ReactNode} from 'react';
export async function generateMetadata(){return {title:(await getServerLanguage())==='en'?'SOMA User Guide':'SOMA 사용 매뉴얼'};}
function inline(text:string):ReactNode[]{return text.split(/(`[^`]+`|\[[^\]]+\]\(https:\/\/[^)]+\))/g).filter(Boolean).map((part,i)=>{if(part.startsWith('`'))return <L as="code" key={i}>{part.slice(1,-1)}</L>;const match=part.match(/^\[([^\]]+)\]\((https:\/\/[^)]+)\)$/);return match?<L as="a" key={i} href={match[2]} target="_blank" rel="noreferrer">{match[1]}</L>:part;});}
export default async function Manual(){const language=await getServerLanguage();const chapters=sourceChapters.map(c=>language==='en'?{...c,...c.en}:c);return <L as="main" className="portal manual-page"><LabHeader active="manual"/><L as="div" className="portal-content"><L as="div" className="portal-heading"><L as="div"><L as="span" className="portal-kicker">SOMA / USER GUIDE</L><L as="h1">사용 매뉴얼</L><L as="p">설치부터 센서 부착까지, 실험 화면을 사용하는 방법.</L></L><BookOpen size={34}/></L><L as="div" className="manual-layout"><L as="aside" className="manual-toc"><L as="nav" aria-label="매뉴얼 목차">{chapters.map((c,i)=><L as="a" key={c.id} href={`#${c.id}`}><L as="small">0{i+1}</L>{c.id==='start'?'처음 시작하기':c.title}</L>)}</L><L as="a" className="manual-launch" href="/simulators/wrist">손목 실험 열기<ArrowUpRight size={16}/></L></L><L as="div">{chapters.map(c=><L as="article" className="manual-chapter" id={c.id} key={c.id}><L as="div" className="manual-chapter-title"><L as="h2">{c.title}</L><L as="a" href={`/documents/manual/${c.id}`} aria-label={`${c.title} 웹 문서 보기`}><FileText size={16}/></L></L>{c.blocks.map((b,i)=>b.type==='heading'?<L as="h3" key={i}>{b.text}</L>:b.type==='list'?<L as="ul" key={i}>{b.items?.map((item,j)=><L as="li" key={j}>{inline(item)}</L>)}</L>:<L as="p" key={i}>{inline(b.text||'')}</L>)}</L>)}</L></L></L></L>}
